project:
  type: website

website:
  title: "예안(YEAN)"
  navbar:
    logo: ./img/yean-logo.png
    left:
      - href: index.qmd
        text: 예안한의원홈
      - text: "질병소개"
        href: docs/blog/index.qmd
      - 예안클리닉.qmd
      - 예안패키지.qmd
      #- 예안치료사례.qmd
      - 예안한의원소개.qmd
  page-footer:
    # left: |
    center: |
      <div style="text-align:center">
      ![](./img/yean-logo-text.png){width=100}
      </div>
      창원시 의창구 사림로 45번길 1  
      055-237-1775  
      Copyright© 예안한의원  
      All Rights Reserved

    # right:
    #   - icon: facebook
    #     href: https://facebook.com/yeanclinic
    #   - icon: instagram  
    #     href: https://instagram.com/yeanclinic
    #   - icon: youtube
    #     href: https://youtube.com/yeanclinic
    background: light
    border: false

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

